---
apiVersion: v2
name: argo-cd
type: application
description: ArgoCD Helm Chart for Kubernetes
appVersion: v0.0.1
version: 0.0.1
keywords:
  - argoproj
  - argocd
  - gitops
dependencies:
  - name: argo-cd
    version: 8.0.1
    repository: https://argoproj.github.io/argo-helm
