{{- if .Values.certificate.enabled }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ .Values.certificate.name }}
  namespace: {{ .Release.Namespace }}
spec:
  secretName: {{ .Values.tlsSecretName }}
  issuerRef:
    name: {{ .Values.certificate.issuer.name }}
    kind: {{ .Values.certificate.issuer.kind }}
  commonName: {{ .Values.subdomain }}.{{ .Values.domain }}
  dnsNames:
    - {{ .Values.subdomain }}.{{ .Values.domain }}
{{- end }}